/**
 * Quote section, itemized fees, loading/error, result cards, and transaction banner styles.
 */

import * as stylex from "@stylexjs/stylex";

export const swapPanelQuoteStyles = stylex.create({
  quoteSection: {
    marginTop: "1.5rem",
    paddingTop: "1.25rem",
    borderTop: "1px solid var(--border)",
  },
  loadingContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
    fontSize: "0.875rem",
    color: "var(--muted-foreground, #666)",
    padding: "0.75rem 0",
  },
  loadingText: {
    fontSize: "0.875rem",
    color: "var(--muted-foreground, #666)",
  },
  gettingQuoteText: {
    fontSize: "0.875rem",
    color: "var(--muted-foreground, #666)",
  },
  errorSection: {
    fontSize: "0.875rem",
  },
  errorMessage: {
    color: "var(--destructive)",
    marginBottom: "0.5rem",
  },
  errorMessageNoMargin: {
    color: "var(--destructive)",
    marginBottom: 0,
  },
  errorHint: {
    color: "var(--muted-foreground, #666)",
    marginTop: 0,
  },
  noRoutesText: {
    fontSize: "0.875rem",
    color: "var(--muted-foreground, #666)",
    marginBottom: "0",
    minHeight: "1.5rem",
  },
  timeoutMessage: {
    fontSize: "0.875rem",
    color: "var(--muted-foreground, #666)",
    marginTop: "0.75rem",
    marginBottom: "0.75rem",
    textAlign: "right",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: "0.25rem",
  },
  quoteDetails: {
    marginBottom: "1rem",
  },
  skeletonSection: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    marginBottom: "1rem",
  },
  itemizedSection: {
    fontSize: "0.875rem",
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
  },
  itemizedRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: "0.5rem",
  },
  itemizedLabel: {
    color: "var(--muted-foreground, #666)",
  },
  itemizedValue: {
    color: "var(--foreground)",
  },
  itemizedValueRed: {
    color: "var(--destructive, #ef4444)",
  },
  itemizedValueGreen: {
    color: "#22c55e",
  },
  itemizedValueBold: {
    fontWeight: 600,
  },
  poweredByRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "0.5rem",
    marginTop: "0.5rem",
    paddingTop: "0.375rem",
    borderTop: "1px solid var(--border)",
    fontSize: "0.8125rem",
  },
  poweredByLabel: {
    color: "var(--muted-foreground, #666)",
  },
  poweredByLogoWrap: {
    width: "1.5rem",
    height: "1.5rem",
    borderRadius: "50%",
    overflow: "hidden",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "var(--background)",
  },
  poweredByLogo: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  itemizedMarginTop: {
    display: "flex",
    justifyContent: "space-between",
    gap: "0.5rem",
    marginTop: "0.25rem",
  },
  otherOptions: {
    fontSize: "0.75rem",
    color: "var(--muted-foreground, #666)",
    marginTop: "0.35rem",
    display: "flex",
    alignItems: "center",
    gap: "0.25rem",
  },
  infoIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "0.875rem",
    height: "0.875rem",
    borderRadius: "50%",
    border: "1px solid var(--muted-foreground)",
    color: "var(--muted-foreground)",
    fontSize: "0.625rem",
    fontWeight: 600,
    cursor: "help",
    flexShrink: 0,
  },
  infoTooltip: {
    position: "relative",
    display: "inline-block",
  },
  resultCard: {
    position: "relative",
    padding: "1rem 1.25rem",
    paddingRight: "2.5rem",
    borderRadius: "var(--radius-sm, 8px)",
    marginTop: "0.75rem",
    marginBottom: "1rem",
    transition: "all 0.2s ease",
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
  },
  resultCardSuccess: {
    background: "rgba(34, 197, 94, 0.08)",
    border: "1px solid rgba(34, 197, 94, 0.25)",
    color: "var(--success, #22c55e)",
  },
  resultCardError: {
    background: "rgba(239, 68, 68, 0.08)",
    border: "1px solid rgba(239, 68, 68, 0.25)",
    color: "var(--destructive, #ef4444)",
  },
  resultCardHeader: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    fontSize: "0.9375rem",
    fontWeight: 600,
  },
  resultCardBody: {
    fontSize: "0.8125rem",
    color: "var(--muted-foreground, #94a3b8)",
    lineHeight: 1.45,
  },
  resultCardBodySuccess: {
    color: "rgba(34, 197, 94, 0.9)",
  },
  resultCardExplorerButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.375rem",
    padding: "0.5rem 0.875rem",
    fontSize: "0.8125rem",
    fontWeight: 500,
    borderRadius: "6px",
    border: "1px solid var(--border, #1e293b)",
    background: "rgba(255, 255, 255, 0.06)",
    color: "var(--foreground, #f4f4f5)",
    textDecoration: "none",
    cursor: "pointer",
    transition: "background 0.15s, border-color 0.15s",
    alignSelf: "flex-start",
    ":hover": {
      background: "rgba(255, 255, 255, 0.1)",
      borderColor: "var(--muted-foreground, #94a3b8)",
    },
  },
  transactionStatusBanner: {
    fontSize: "0.875rem",
    padding: "1rem 1.25rem",
    borderRadius: "var(--radius-sm, 8px)",
    marginTop: "0.75rem",
    display: "flex",
    flexDirection: "column",
    gap: "0.625rem",
    transition: "all 0.2s ease",
  },
  transactionStatusRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  transactionStatusPending: {
    backgroundColor: "rgba(59, 130, 246, 0.08)",
    border: "1px solid rgba(59, 130, 246, 0.25)",
    color: "#60a5fa",
  },
  transactionStatusConfirmed: {
    backgroundColor: "rgba(34, 197, 94, 0.08)",
    border: "1px solid rgba(34, 197, 94, 0.25)",
    color: "#4ade80",
  },
  transactionStatusFinalized: {
    backgroundColor: "rgba(34, 197, 94, 0.08)",
    border: "1px solid rgba(34, 197, 94, 0.25)",
    color: "#22c55e",
  },
  transactionStatusFailed: {
    backgroundColor: "rgba(239, 68, 68, 0.08)",
    border: "1px solid rgba(239, 68, 68, 0.25)",
    color: "#f87171",
  },
  transactionLink: {
    display: "inline-flex",
    alignItems: "center",
    padding: "0.5rem 0.875rem",
    fontSize: "0.8125rem",
    fontWeight: 500,
    borderRadius: "6px",
    border: "1px solid var(--border, #1e293b)",
    background: "rgba(255, 255, 255, 0.06)",
    color: "inherit",
    textDecoration: "none",
    cursor: "pointer",
    transition: "background 0.15s, border-color 0.15s",
    alignSelf: "flex-start",
  },
  statusIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "1.25rem",
    height: "1.25rem",
    borderRadius: "50%",
    fontSize: "0.75rem",
    fontWeight: 600,
    flexShrink: 0,
  },
  dismissMessageButton: {
    position: "absolute",
    top: "0.5rem",
    right: "0.5rem",
    padding: "0.25rem",
    border: "none",
    borderRadius: "4px",
    background: "transparent",
    color: "inherit",
    opacity: 0.7,
    cursor: "pointer",
    fontSize: "1rem",
    lineHeight: 1,
  },
});
