/**
 * Form, input, and button styles for SwapPanel (PaySection, ReceiveSection, warnings).
 */

import * as stylex from "@stylexjs/stylex";

export const swapPanelFormStyles = stylex.create({
  inputSection: {
    padding: "1rem",
    borderRadius: "16px",
    border: "none",
    background: "transparent",
    marginBottom: "0.75rem",
  },
  inputHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "0.5rem",
  },
  inputLabel: {
    fontSize: "0.75rem",
    color: "var(--muted-foreground)",
    fontWeight: 500,
    width: "80px",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    height: "100%",
    lineHeight: "1.5",
  },
  chainBadge: {
    display: "inline-flex",
    alignItems: "center",
    padding: "0.2rem 0.5rem",
    borderRadius: "6px",
    background: "var(--muted)",
    color: "var(--muted-foreground)",
  },
  solanaIcon: {
    display: "block",
  },
  inputRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "0.75rem",
    paddingLeft: "0.75rem",
    paddingRight: "0",
  },
  inputAmountWrapper: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
    background: "transparent",
    minWidth: 0,
  },
  inputHeaderRow: {
    display: "flex",
    alignItems: "center",
    marginBottom: "0.5rem",
    paddingLeft: "0.75rem",
    paddingRight: "0",
  },
  tokenSelectContainer: {
    flexShrink: 0,
    minWidth: "170px",
    width: "170px",
    minHeight: "2.5rem",
    display: "flex",
    alignItems: "center",
  },
  inputGroup: {
    width: "100%",
  },
  inputGroupWide: {
    width: "100%",
  },
  balanceText: {
    fontSize: "0.75rem",
    color: "var(--muted-foreground)",
    marginTop: "0.25rem",
    paddingLeft: "0.75rem",
  },
  amountInput: {
    width: "100%",
    padding: "0 0.75rem",
    margin: "0",
    borderRadius: "var(--radius-sm)",
    border: "none",
    background: "transparent",
    backgroundColor: "transparent",
    color: "var(--foreground)",
    fontSize: "2rem",
    fontWeight: 500,
    boxSizing: "border-box",
    outline: "none",
    lineHeight: 1.2,
    WebkitAppearance: "none",
    MozAppearance: "textfield",
    appearance: "none",
  },
  amountInputReadOnly: {
    color: "var(--muted-foreground)",
  },
  rawAmountHint: {
    fontSize: "0.7rem",
    color: "var(--muted-foreground)",
    marginTop: "0.35rem",
  },
  warningIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    width: "1.25rem",
    height: "1.25rem",
    color: "var(--destructive)",
  },
  toSection: {
    padding: "1rem",
    borderRadius: "16px",
    border: "none",
    background: "transparent",
    marginBottom: "0.75rem",
  },
  toHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "0.5rem",
  },
  toLabel: {
    fontSize: "0.75rem",
    color: "var(--muted-foreground)",
    fontWeight: 500,
    width: "80px",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    height: "100%",
    lineHeight: "1.5",
  },
  toAmountRow: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    marginBottom: "0.25rem",
  },
  toAmountHeaderRow: {
    display: "flex",
    alignItems: "center",
    marginBottom: "0.5rem",
    paddingLeft: "0.75rem",
    paddingRight: "0",
  },
  toAmountContent: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "0.75rem",
    paddingLeft: "0.75rem",
    paddingRight: "0",
  },
  toAmountWrapper: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
    background: "transparent",
    minWidth: 0,
  },
  destinationSelectorContainer: {
    flexShrink: 0,
    minWidth: "170px",
    width: "170px",
    minHeight: "2.5rem",
    display: "flex",
    alignItems: "center",
  },
  receiveAmount: {
    fontSize: "2rem",
    fontWeight: 500,
    color: "var(--foreground)",
    lineHeight: 1.2,
  },
  receiveAmountPlaceholder: {
    fontSize: "2rem",
    fontWeight: 500,
    color: "var(--muted-foreground)",
    lineHeight: 1.2,
  },
  receiveCaption: {
    fontSize: "0.75rem",
    color: "var(--muted-foreground)",
    marginTop: "0.15rem",
  },
  toInputRow: {
    display: "flex",
    gap: "0.75rem",
    alignItems: "flex-start",
    marginTop: "0.5rem",
    flexWrap: "wrap",
  },
  errorText: {
    fontSize: "0.75rem",
    color: "var(--destructive)",
    marginBottom: "0.25rem",
  },
  warningBanner: {
    fontSize: "0.875rem",
    color: "#f59e0b",
    backgroundColor: "rgba(245, 158, 11, 0.1)",
    border: "1px solid rgba(245, 158, 11, 0.3)",
    borderRadius: "8px",
    padding: "0.75rem",
    marginBottom: "0.75rem",
    display: "flex",
    alignItems: "flex-start",
    gap: "0.5rem",
    transition: "all 0.3s ease",
  },
  errorLink: {
    color: "var(--primary)",
    textDecoration: "underline",
    textDecorationThickness: "1px",
    textUnderlineOffset: "2px",
    cursor: "pointer",
    display: "inline",
  },
  invalidRouteText: {
    fontSize: "0.75rem",
    color: "var(--muted-foreground, #666)",
    marginBottom: "0.5rem",
  },
  expiryIndicator: {
    fontSize: "0.75rem",
    marginTop: "0.5rem",
    display: "flex",
    alignItems: "center",
    gap: "0.25rem",
  },
  expiryIndicatorWarning: {
    color: "#f59e0b",
  },
  expiryIndicatorExpired: {
    color: "var(--destructive)",
  },
  expiryIndicatorNormal: {
    color: "var(--muted-foreground, #666)",
  },
  actionRow: {
    display: "flex",
    gap: "0.5rem",
    flexWrap: "wrap",
    alignItems: "center",
    marginTop: "1rem",
    minHeight: "3rem",
  },
  insufficientSolText: {
    fontSize: "0.8rem",
    color: "var(--destructive, #b91c1c)",
    display: "inline-flex",
    alignItems: "center",
    gap: "0.5rem",
    flexWrap: "wrap",
  },
  insufficientFundsButton: {
    padding: "1rem 1.5rem",
    borderRadius: "16px",
    fontSize: "1rem",
    fontWeight: 600,
    cursor: "not-allowed",
    opacity: 0.5,
    width: "100%",
    textAlign: "center",
    background: "rgba(255, 255, 255, 0.05)",
    border: "none",
    color: "var(--muted-foreground)",
    transition: "all 0.2s ease",
  },
  refreshButton: {
    textDecoration: "underline",
    background: "none",
    border: "none",
    color: "inherit",
    cursor: "pointer",
    padding: 0,
    fontSize: "inherit",
  },
  swapButton: {
    padding: "1rem 1.5rem",
    borderRadius: "16px",
    fontSize: "1rem",
    fontWeight: 600,
    cursor: "pointer",
    width: "100%",
    textAlign: "center",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    border: "none",
    color: "#ffffff",
    transition: "all 0.2s ease",
    boxShadow: "0 4px 12px rgba(102, 126, 234, 0.3)",
    ":hover:not(:disabled)": {
      transform: "translateY(-2px)",
      boxShadow: "0 6px 20px rgba(102, 126, 234, 0.4)",
      background: "linear-gradient(135deg, #7c8ef0 0%, #8a5fb8 100%)",
    },
    ":active:not(:disabled)": {
      transform: "translateY(0)",
      boxShadow: "0 2px 8px rgba(102, 126, 234, 0.3)",
    },
  },
  swapButtonDisabled: {
    cursor: "not-allowed",
    opacity: 0.5,
    background: "rgba(255, 255, 255, 0.05)",
    boxShadow: "none",
  },
});
